@port=3000
@jwt={{login.response.body.data.token}}

###
GET http://localhost:{{port}}/api/v1/workouts
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts
Authorization: Bearer {{jwt}}

###

GET http://localhost:{{port}}/api/v1/workouts/getWorkoutsTest
Authorization: Bearer {{jwt}}


###

GET http://localhost:{{port}}/api/v1/workouts/fillWorkouts
Authorization: Bearer {{jwt}}

###


GET http://localhost:{{port}}/api/v1/workouts/fillAllWorkouts
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/search/legs
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/removeWorkoutFromTable/2
Authorization: Bearer {{jwt}}

###

GET http://localhost:{{port}}/api/v1/workouts/getWorkoutById/100
Authorization: Bearer {{jwt}}


###
POST http://localhost:{{port}}/api/v1/workouts?workoutTitle="Cardio"
Content-Type: application/json

{
    "sets": 3,
    "rest": 60,
    "supersets": true,
    "squats": 3,
    "lunges": 10,
    "leg press": 10  
}




###
GET http://localhost:{{port}}/api/v1/workouts/getUserWorkouts/tanner
Authorization: Bearer {{jwt}}

###


###
GET http://localhost:{{port}}/api/v1/workouts/removeWorkout/0
Authorization: Bearer {{jwt}}

###
POST http://localhost:{{port}}/api/v1/workouts/addWorkout
Content-Type: application/json

{
    "username": "tanner",
    "workoutType": "test",
    "description": "test",
    "intensity": "Normal"
}

###
POST http://localhost:{{port}}/api/v1/workouts/editWorkoutById
Content-Type: application/json

{
    "description": "hey stones",
    "intensity": "High",
    "id": 1
}

###
GET http://localhost:{{port}}/api/v1/workouts/getFriendsActivities
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/getWorkoutsPrData/humza
Authorization: Bearer {{jwt}}

###
POST http://localhost:{{port}}/api/v1/users/seed
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/users
Authorization: Bearer {{jwt}}

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "123456"
}