###
GET http://localhost:3000/api/models/users
###
GET http://localhost:3000/api/dummy
###
GET http://localhost:3000/api/models/deleteDBs
###
GET http://localhost:3000/api/models/updateUser
###
# Update tannerfesta@gmail's tags to be 1
GET http://localhost:3000/api/models/updateUser?email=tannerfesta@gmail.com&parameterToUpdate=tags&newValue=1&parameterType=number
###
# Notice we left out the last parameter since it's a string by default
# Updates tannerfesta@gmail.com nickname
GET http://localhost:3000/api/models/updateUser?email=tannerfesta@gmail.com&parameterToUpdate=nickname&newValue=Hey%20There
# %20 is a space
###
# Allow tannerfesta@gmail.com to be in weeklong
GET http://localhost:3000/api/models/updateUser?email=tannerfesta@gmail.com&parameterToUpdate=isInWeeklong&newValue=false&parameterType=boolean
###
# Update tannerfesta@gmail.com to admin
GET http://localhost:3000/api/models/updateUser?email=tannerfesta@gmail.com&parameterToUpdate=isAdmin&newValue=true&parameterType=boolean
